security:
    resource: "@SecurityBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"

json_rpc:
    resource: "@JsonRpcBundle/Resources/config/routing.yml"