security:
    providers:
        access_service:
            id: access.user_provider
    encoders:
        AccessBundle\User: 
            algorithm: sha512
            encode_as_base64: false
            iterations: 0

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        login:
            pattern: ^/login
            security: false
        app:
            pattern: .*
            form_login:
                check_path: /check
                login_path: /login
            logout:
                path: /logout
                target: /dashboard
                