imports:
    - { resource: "@AppBundle/Resources/config/services.yml" }


services:
    kernel.listener.json_rpc:
        class: AppBundle\EventListener\UserRequestListener
        calls:
            -   [ setService, [@app.jsonrpc]]
        tags:
            -   { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

