parameters:
    enable_json_logging: on;

services:
    json_rpc.server:
        class: JsonRpcBundle\Server
        calls:
            - [setContainer, ["@service_container"]]
        arguments: ["@logger", "%enable_json_logging%"]
        tags:
            - { name: monolog.logger, channel: jsonrpc }
