parameters:
    jsonrpcs:
            functions:
                    getprod:
                        service:    "app.warehouse"
                        method:     "getProductStocks"
                    getall:
                        service:    "app.warehouse"
                        method:     "getAll"
                    getcat:
                        service:    "app.catalog"
                        method:     "getCategories"
services:
    app.listener.soft_delete:
        class: AppBundle\Event\Listener\SoftDelete
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    app.doctrine_aware:
        class: AppBundle\Service\AbstractDoctrineAware
        arguments: [@doctrine, @?logger]
        abstract: true

    app.warehouse:
        class: AppBundle\Service\WarehouseService
        parent: app.doctrine_aware

    app.catalog:
        class: AppBundle\Service\CatalogService
        parent: app.doctrine_aware

    app.jsonrpc:
        class: AppBundle\Service\JsonRPCService
        arguments: [%jsonrpcs%]