services:
    app.listener.soft_delete:
        class: AppBundle\Event\Listener\SoftDelete
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            
    app.warehouse:
        class: AppBundle\Service\WarehouseService
        arguments: [@service_container]